# Generated by OmopViewer 0.3.0
# Be careful editing this file

server <- function(input, output, session) {
  # summary ----
  output$summary_cdm_name <- shinyTree::renderTree(summaryCdmName(data))
  output$summary_packages <- shinyTree::renderTree(summaryPackages(data))
  output$summary_min_cell_count <- shinyTree::renderTree(summaryMinCellCount(data))
  output$summary_panels <- shinyTree::renderTree(summaryPanels(data))
  # download raw data -----
  output$download_raw <- shiny::downloadHandler(
    filename = "results.csv",
    content = function(file) {
      data |>
        omopgenerics::bind() |>
        omopgenerics::exportSummarisedResult(fileName = file)
    }
  )
  # summarise_omop_snapshot -----
  ## get summarise_omop_snapshot data
  getSummariseOmopSnapshotData <- shiny::reactive({
    data[["summarise_omop_snapshot"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_omop_snapshot_cdm_name,
        .data$variable_name %in% input$summarise_omop_snapshot_variable_name
      )
  })
  getSummariseOmopSnapshotTidy <- shiny::reactive({
    tidyDT(getSummariseOmopSnapshotData(), input$summarise_omop_snapshot_tidy_columns, input$summarise_omop_snapshot_tidy_pivot_estimates)
  })
  output$summarise_omop_snapshot_tidy <- DT::renderDT({
    getSummariseOmopSnapshotTidy()
  })
  output$summarise_omop_snapshot_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getSummariseOmopSnapshotData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getSummariseOmopSnapshotTable <- shiny::reactive({
    getSummariseOmopSnapshotData() |>
      OmopSketch::tableOmopSnapshot()
  })
  output$summarise_omop_snapshot_table <- gt::render_gt({
    getSummariseOmopSnapshotTable()
  })
  output$summarise_omop_snapshot_table_download <- shiny::downloadHandler(
    filename = paste0("table_snapshot.", input$summarise_omop_snapshot_table_format),
    content = function(file) {
      gt::gtsave(getSummariseOmopSnapshotTable(), file)
    }
  )
  # summarise_observation_period -----
  ## get summarise_observation_period data
  getSummariseObservationPeriodData <- shiny::reactive({
    data[["summarise_observation_period"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_observation_period_cdm_name,
        .data$variable_name %in% input$summarise_observation_period_variable_name,
        .data$estimate_name %in% input$summarise_observation_period_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$observation_period_ordinal %in% input$summarise_observation_period_observation_period_ordinal)
  })
  getSummariseObservationPeriodTidy <- shiny::reactive({
    tidyDT(getSummariseObservationPeriodData(), input$summarise_observation_period_tidy_columns, input$summarise_observation_period_tidy_pivot_estimates)
  })
  output$summarise_observation_period_tidy <- DT::renderDT({
    getSummariseObservationPeriodTidy()
  })
  output$summarise_observation_period_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getSummariseObservationPeriodData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getSummariseObservationPeriodTable <- shiny::reactive({
    getSummariseObservationPeriodData() |>
      OmopSketch::tableObservationPeriod()
  })
  output$summarise_observation_period_table <- gt::render_gt({
    getSummariseObservationPeriodTable()
  })
  output$summarise_observation_period_table_download <- shiny::downloadHandler(
    filename = paste0("table_obsevation_period.", input$summarise_observation_period_table_format),
    content = function(file) {
      gt::gtsave(getSummariseObservationPeriodTable(), file)
    }
  )
  getSummariseObservationPeriodPlot <- shiny::reactive({
    getSummariseObservationPeriodData() |>
      OmopSketch::plotObservationPeriod(
        variableName = input$summarise_observation_period_plot_variable,
        plotType = input$summarise_observation_period_plot_plot_type,
        facet = input$summarise_observation_period_plot_facet,
        colour = input$summarise_observation_period_plot_colour
      )
  })
  output$summarise_observation_period_plot <- shiny::renderUI({
    renderInteractivePlot(getSummariseObservationPeriodPlot(), input$summarise_observation_period_plot_interactive)
  })
  output$summarise_observation_period_plot_download <- shiny::downloadHandler(
    filename = "plot_observation_period.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseObservationPeriodPlot(),
        width = as.numeric(input$summarise_observation_period_plot_width),
        height = as.numeric(input$summarise_observation_period_plot_height),
        units = input$summarise_observation_period_plot_units,
        dpi = as.numeric(input$summarise_observation_period_plot_dpi)
      )
    }
  )
  # cohort_code_use -----
  ## get cohort_code_use data
  getCohortCodeUseData <- shiny::reactive({
    data[["cohort_code_use"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$cohort_code_use_cdm_name,
        .data$variable_name %in% input$cohort_code_use_variable_name,
        .data$estimate_name %in% input$cohort_code_use_estimate_name
      ) |>
      omopgenerics::filterGroup(
        .data$cohort_name %in% input$cohort_code_use_cohort_name,
        .data$codelist_name %in% input$cohort_code_use_codelist_name
      )
  })
  getCohortCodeUseTidy <- shiny::reactive({
    tidyDT(getCohortCodeUseData(), input$cohort_code_use_tidy_columns, input$cohort_code_use_tidy_pivot_estimates)
  })
  output$cohort_code_use_tidy <- DT::renderDT({
    getCohortCodeUseTidy()
  })
  output$cohort_code_use_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getCohortCodeUseData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getCohortCodeUseTable <- shiny::reactive({
    getCohortCodeUseData() |>
      CodelistGenerator::tableCohortCodeUse(
        timing = TRUE,
        header = input$cohort_code_use_table_header,
        groupColumn = input$cohort_code_use_table_group_column,
        hide = input$cohort_code_use_table_hide
      )
  })
  output$cohort_code_use_table <- gt::render_gt({
    getCohortCodeUseTable()
  })
  output$cohort_code_use_table_download <- shiny::downloadHandler(
    filename = paste0("table_cohort_code_use.", input$cohort_code_use_table_format),
    content = function(file) {
      gt::gtsave(getCohortCodeUseTable(), file)
    }
  )
  # summarise_characteristics -----
  ## get summarise_characteristics data
  getSummariseCharacteristicsData <- shiny::reactive({
    data[["summarise_characteristics"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_characteristics_cdm_name,
        .data$variable_name %in% input$summarise_characteristics_variable_name,
        .data$estimate_name %in% input$summarise_characteristics_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_characteristics_cohort_name)
  })
  getSummariseCharacteristicsTidy <- shiny::reactive({
    tidyDT(getSummariseCharacteristicsData(), input$summarise_characteristics_tidy_columns, input$summarise_characteristics_tidy_pivot_estimates)
  })
  output$summarise_characteristics_tidy <- DT::renderDT({
    getSummariseCharacteristicsTidy()
  })
  output$summarise_characteristics_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getSummariseCharacteristicsData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getSummariseCharacteristicsTable <- shiny::reactive({
    getSummariseCharacteristicsData() |>
      CohortCharacteristics::tableCharacteristics(
        header = input$summarise_characteristics_table_header,
        groupColumn = input$summarise_characteristics_table_group_column,
        hide = input$summarise_characteristics_table_hide
      )
  })
  output$summarise_characteristics_table <- gt::render_gt({
    getSummariseCharacteristicsTable()
  })
  output$summarise_characteristics_table_download <- shiny::downloadHandler(
    filename = paste0("table_characteristics.", input$summarise_characteristics_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCharacteristicsTable(), file)
    }
  )
  getSummariseCharacteristicsPlot <- shiny::reactive({
    getSummariseCharacteristicsData() |>
      CohortCharacteristics::plotCharacteristics(
        plotType = input$summarise_characteristics_plot_plot_type,
        facet = input$summarise_characteristics_plot_facet,
        colour = input$summarise_characteristics_plot_colour
      )
  })
  output$summarise_characteristics_plot <- shiny::renderUI({
    renderInteractivePlot(getSummariseCharacteristicsPlot(), input$summarise_characteristics_plot_interactive)
  })
  output$summarise_characteristics_plot_download <- shiny::downloadHandler(
    filename = "plot_characteristics.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseCharacteristicsPlot(),
        width = as.numeric(input$summarise_characteristics_plot_width),
        height = as.numeric(input$summarise_characteristics_plot_height),
        units = input$summarise_characteristics_plot_units,
        dpi = as.numeric(input$summarise_characteristics_plot_dpi)
      )
    }
  )
  # summarise_large_scale_characteristics -----
  ## get summarise_large_scale_characteristics data
  getSummariseLargeScaleCharacteristicsData <- shiny::reactive({
    data[["summarise_large_scale_characteristics"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_large_scale_characteristics_cdm_name,
        .data$variable_level %in% input$summarise_large_scale_characteristics_variable_level
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_large_scale_characteristics_cohort_name) |>
      omopgenerics::filterSettings(
        .data$analysis %in% input$summarise_large_scale_characteristics_analysis,
        .data$table_name %in% input$summarise_large_scale_characteristics_table_name,
        .data$type %in% input$summarise_large_scale_characteristics_type
      )
  })
  getSummariseLargeScaleCharacteristics <- shiny::reactive({
    if (identical(input$summarise_large_scale_characteristics__compare_by, "no compare")) {
      cb <- NULL
    } else {
      cb <- input$summarise_large_scale_characteristics__compare_by
    }
    if (identical(input$summarise_large_scale_characteristics__smd_reference, "no SMD")) {
      sr <- NULL
    } else {
      sr <- input$summarise_large_scale_characteristics__smd_reference
    }
    getSummariseLargeScaleCharacteristicsData() |>
      tableLargeScaleCharacteristics(
        compareBy = cb,
        hide = input$summarise_large_scale_characteristics__hide,
        smdReference = sr
      )
  })
  output$summarise_large_scale_characteristics_ <- reactable::renderReactable({
    getSummariseLargeScaleCharacteristics()
  })
  shiny::observeEvent(input$summarise_large_scale_characteristics__compare_by, {
    opts <- values[[paste0("summarise_large_scale_characteristics_", input$summarise_large_scale_characteristics__compare_by)]]
    opts <- c("no SMD", opts)
    shinyWidgets::updatePickerInput(
      inputId = "summarise_large_scale_characteristics__smd_reference",
      choices = opts,
      selected = "no SMD"
    )
  })
  output$summarise_large_scale_characteristics__download <- shiny::downloadHandler(
    filename = character(),
    content = function(file) {

    }
  )
  getSummariseLargeScaleCharacteristicsTableMostCommon <- shiny::reactive({
    getSummariseLargeScaleCharacteristicsData() |>
      tableTopLargeScaleCharacteristics(
        topConcepts = input$summarise_large_scale_characteristics_table_most_common_top_concepts
      )
  })
  output$summarise_large_scale_characteristics_table_most_common <- gt::render_gt({
    getSummariseLargeScaleCharacteristicsTableMostCommon()
  })
  output$summarise_large_scale_characteristics_table_most_common_download <- shiny::downloadHandler(
    filename = character(),
    content = function(file) {

    }
  )
  getSummariseLargeScaleCharacteristicsPlotCompared <- shiny::reactive({
    getSummariseLargeScaleCharacteristicsData() |>
      plotComparedLargeScaleCharacteristics(
        colour = input$summarise_large_scale_characteristics_plot_compared_colour,
        reference = input$summarise_large_scale_characteristics_plot_compared_reference,
        facet = input$summarise_large_scale_characteristics_plot_compared_facet
      )
  })
  output$summarise_large_scale_characteristics_plot_compared <- plotly::renderPlotly({
    getSummariseLargeScaleCharacteristicsPlotCompared()
  })
  shiny::observeEvent(input$summarise_large_scale_characteristics_plot_compared_colour, {
    opts <- values[[paste0("summarise_large_scale_characteristics_", input$summarise_large_scale_characteristics_plot_compared_colour)]]
    shinyWidgets::updatePickerInput(
      inputId = "summarise_large_scale_characteristics_plot_compared_reference",
      choices = opts,
      selected = opts[1]
    )
  })
  output$summarise_large_scale_characteristics_plot_compared_download <- shiny::downloadHandler(
    filename = character(),
    content = function(file) {

    }
  )
}
