# Generated by OmopViewer 0.2.0
# Be careful editing this file

ui <- bslib::page_navbar(
  title = shiny::tags$span(
    shiny::tags$img(
      src = "ohdsi_logo.svg",
      width = "auto",
      height = "46px",
      class = "me-3",
      alt = "logo"
    ),
    ""
  ),
  theme = bslib::bs_theme(),
  bslib::nav_panel(
    title = "Background",
    icon = shiny::icon("disease"),
    backgroundCard("background.md")
  ),
  bslib::nav_panel(
    title = "Summary",
    icon = shiny::icon("file-alt"),
    summaryCard(data)
  ),
  bslib::nav_menu(
    title = "Databases",
    icon = shiny::icon("list"),
    bslib::nav_panel(
      title = "Snapshot",
      icon = shiny::icon("clipboard-list"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::accordion(
            bslib::accordion_panel(
              title = "Grouping",
              shinyWidgets::pickerInput(
                inputId = "summarise_omop_snapshot_grouping_cdm_name",
                label = "Cdm name",
                choices = filterValues$summarise_omop_snapshot_grouping_cdm_name,
                selected = filterValues$summarise_omop_snapshot_grouping_cdm_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Variables",
              shinyWidgets::pickerInput(
                inputId = "summarise_omop_snapshot_variable_name",
                label = "Variable name",
                choices = filterValues$summarise_omop_snapshot_variable_name,
                selected = filterValues$summarise_omop_snapshot_variable_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Estimates",
              shinyWidgets::pickerInput(
                inputId = "summarise_omop_snapshot_estimate_name",
                label = "Estimate name",
                choices = filterValues$summarise_omop_snapshot_estimate_name,
                selected = filterValues$summarise_omop_snapshot_estimate_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            )
          )
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Tidy",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::downloadButton(outputId = "summarise_omop_snapshot_tidy_download", label = "Download csv")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_omop_snapshot_tidy_columns",
                    label = "Columns",
                    choices = filterValues$summarise_omop_snapshot_tidy_columns,
                    selected = filterValues$summarise_omop_snapshot_tidy_columns,
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::radioButtons(
                    inputId = "summarise_omop_snapshot_tidy_pivot",
                    label = "Pivot estimates/variables",
                    choices = c("none", "estimates", "estimates and variables"),
                    selected = "none"
                  ),
                  position = "right"
                ),
                DT::dataTableOutput("summarise_omop_snapshot_tidy")
              )
            )
          ),
          bslib::nav_panel(
            title = "Snapshot table",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_omop_snapshot_gt_17_download_type",
                    label = "File type",
                    selected = "docx",
                    choices = c("docx", "png", "pdf", "html"),
                    multiple = FALSE
                  ),
                  shiny::downloadButton(outputId = "summarise_omop_snapshot_gt_17_download", label = "Download")
                ),
                class = "text-end"
              ),
              gt::gt_output("summarise_omop_snapshot_gt_17")
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Observation period",
      icon = shiny::icon("eye"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::accordion(
            bslib::accordion_panel(
              title = "Grouping",
              shinyWidgets::pickerInput(
                inputId = "summarise_observation_period_grouping_cdm_name",
                label = "Cdm name",
                choices = filterValues$summarise_observation_period_grouping_cdm_name,
                selected = filterValues$summarise_observation_period_grouping_cdm_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "summarise_observation_period_grouping_observation_period_ordinal",
                label = "Observation period ordinal",
                choices = filterValues$summarise_observation_period_grouping_observation_period_ordinal,
                selected = filterValues$summarise_observation_period_grouping_observation_period_ordinal,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Variables",
              shinyWidgets::pickerInput(
                inputId = "summarise_observation_period_variable_name",
                label = "Variable name",
                choices = filterValues$summarise_observation_period_variable_name,
                selected = filterValues$summarise_observation_period_variable_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Estimates",
              shinyWidgets::pickerInput(
                inputId = "summarise_observation_period_estimate_name",
                label = "Estimate name",
                choices = filterValues$summarise_observation_period_estimate_name,
                selected = filterValues$summarise_observation_period_estimate_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            )
          )
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Tidy",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::downloadButton(outputId = "summarise_observation_period_tidy_download", label = "Download csv")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_tidy_columns",
                    label = "Columns",
                    choices = filterValues$summarise_observation_period_tidy_columns,
                    selected = filterValues$summarise_observation_period_tidy_columns,
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::radioButtons(
                    inputId = "summarise_observation_period_tidy_pivot",
                    label = "Pivot estimates/variables",
                    choices = c("none", "estimates", "estimates and variables"),
                    selected = "none"
                  ),
                  position = "right"
                ),
                DT::dataTableOutput("summarise_observation_period_tidy")
              )
            )
          ),
          bslib::nav_panel(
            title = "Table observation period",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_gt_15_download_type",
                    label = "File type",
                    selected = "docx",
                    choices = c("docx", "png", "pdf", "html"),
                    multiple = FALSE
                  ),
                  shiny::downloadButton(outputId = "summarise_observation_period_gt_15_download", label = "Download")
                ),
                class = "text-end"
              ),
              gt::gt_output("summarise_observation_period_gt_15")
            )
          ),
          bslib::nav_panel(
            title = "Plot observation period",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_observation_period_ggplot2_16_download_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_observation_period_ggplot2_16_download_height",
                    label = "Height",
                    value = 10
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_ggplot2_16_download_units",
                    label = "Units",
                    selected = "cm",
                    choices = c("px", "cm", "inch"),
                    multiple = FALSE
                  ),
                  shiny::numericInput(
                    inputId = "summarise_observation_period_ggplot2_16_download_dpi",
                    label = "dpi",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_observation_period_ggplot2_16_download", label = "Download")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_ggplot2_16_variableName",
                    label = "variableName",
                    selected = "Number subjects",
                    multiple = ,
                    choices = c("number subjects", "records per person", "duration in days", "days to next observation period"),
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_ggplot2_16_plotType",
                    label = "plotType",
                    selected = "barplot",
                    multiple = ,
                    choices = c("barplot", "boxplot", "densityplot"),
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_ggplot2_16_facet",
                    label = "facet",
                    selected = NULL,
                    multiple = TRUE,
                    choices = c("cdm_name", "observation_period_ordinal"),
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::plotOutput("summarise_observation_period_ggplot2_16")
              )
            )
          )
        )
      )
    )
  ),
  bslib::nav_menu(
    title = "Cohorts",
    icon = shiny::icon("list"),
    bslib::nav_panel(
      title = "Cohort count",
      icon = shiny::icon("users"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::accordion(
            bslib::accordion_panel(
              title = "Settings",
              shinyWidgets::pickerInput(
                inputId = "summarise_cohort_count_settings_table_name",
                label = "Table name",
                choices = filterValues$summarise_cohort_count_settings_table_name,
                selected = filterValues$summarise_cohort_count_settings_table_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Grouping",
              shinyWidgets::pickerInput(
                inputId = "summarise_cohort_count_grouping_cdm_name",
                label = "Cdm name",
                choices = filterValues$summarise_cohort_count_grouping_cdm_name,
                selected = filterValues$summarise_cohort_count_grouping_cdm_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "summarise_cohort_count_grouping_cohort_name",
                label = "Cohort name",
                choices = filterValues$summarise_cohort_count_grouping_cohort_name,
                selected = filterValues$summarise_cohort_count_grouping_cohort_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Variables",
              shinyWidgets::pickerInput(
                inputId = "summarise_cohort_count_variable_name",
                label = "Variable name",
                choices = filterValues$summarise_cohort_count_variable_name,
                selected = filterValues$summarise_cohort_count_variable_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Estimates",
              shinyWidgets::pickerInput(
                inputId = "summarise_cohort_count_estimate_name",
                label = "Estimate name",
                choices = filterValues$summarise_cohort_count_estimate_name,
                selected = filterValues$summarise_cohort_count_estimate_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            )
          )
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Tidy",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::downloadButton(outputId = "summarise_cohort_count_tidy_download", label = "Download csv")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_count_tidy_columns",
                    label = "Columns",
                    choices = filterValues$summarise_cohort_count_tidy_columns,
                    selected = filterValues$summarise_cohort_count_tidy_columns,
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::radioButtons(
                    inputId = "summarise_cohort_count_tidy_pivot",
                    label = "Pivot estimates/variables",
                    choices = c("none", "estimates", "estimates and variables"),
                    selected = "none"
                  ),
                  position = "right"
                ),
                DT::dataTableOutput("summarise_cohort_count_tidy")
              )
            )
          ),
          bslib::nav_panel(
            title = "Table cohort count",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_count_gt_9_download_type",
                    label = "File type",
                    selected = "docx",
                    choices = c("docx", "png", "pdf", "html"),
                    multiple = FALSE
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_count_gt_9_download", label = "Download")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "none",
                      labels = c("cdm_name", "variable_name", "variable_level", "estimate_name"),
                      input_id = "summarise_cohort_count_gt_9_none"
                    ),
                    sortable::add_rank_list(
                      text = "header",
                      labels = "cohort_name",
                      input_id = "summarise_cohort_count_gt_9_header"
                    ),
                    sortable::add_rank_list(
                      text = "groupColumn",
                      labels = character(),
                      input_id = "summarise_cohort_count_gt_9_groupColumn"
                    ),
                    sortable::add_rank_list(
                      text = "hide",
                      labels = character(),
                      input_id = "summarise_cohort_count_gt_9_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_cohort_count_gt_9")
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot cohort count",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_cohort_count_ggplot2_10_download_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_cohort_count_ggplot2_10_download_height",
                    label = "Height",
                    value = 10
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_count_ggplot2_10_download_units",
                    label = "Units",
                    selected = "cm",
                    choices = c("px", "cm", "inch"),
                    multiple = FALSE
                  ),
                  shiny::numericInput(
                    inputId = "summarise_cohort_count_ggplot2_10_download_dpi",
                    label = "dpi",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_count_ggplot2_10_download", label = "Download")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_count_ggplot2_10_facet",
                    label = "facet",
                    selected = "cdm_name",
                    multiple = TRUE,
                    choices = c("cdm_name", "cohort_name", "variable_name", "variable_level", "estimate_name"),
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_count_ggplot2_10_colour",
                    label = "colour",
                    selected = NULL,
                    multiple = TRUE,
                    choices = c("cdm_name", "cohort_name", "variable_name", "variable_level", "estimate_name"),
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::plotOutput("summarise_cohort_count_ggplot2_10")
              )
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Cohort Attrition",
      icon = shiny::icon("layer-group"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::accordion(
            bslib::accordion_panel(
              title = "Settings",
              shinyWidgets::pickerInput(
                inputId = "summarise_cohort_attrition_settings_cdm_version",
                label = "Cdm version",
                choices = filterValues$summarise_cohort_attrition_settings_cdm_version,
                selected = filterValues$summarise_cohort_attrition_settings_cdm_version,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "summarise_cohort_attrition_settings_cohort_definition_id",
                label = "Cohort definition id",
                choices = filterValues$summarise_cohort_attrition_settings_cohort_definition_id,
                selected = filterValues$summarise_cohort_attrition_settings_cohort_definition_id,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "summarise_cohort_attrition_settings_table_name",
                label = "Table name",
                choices = filterValues$summarise_cohort_attrition_settings_table_name,
                selected = filterValues$summarise_cohort_attrition_settings_table_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "summarise_cohort_attrition_settings_vocabulary_version",
                label = "Vocabulary version",
                choices = filterValues$summarise_cohort_attrition_settings_vocabulary_version,
                selected = filterValues$summarise_cohort_attrition_settings_vocabulary_version,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Grouping",
              shinyWidgets::pickerInput(
                inputId = "summarise_cohort_attrition_grouping_cdm_name",
                label = "Cdm name",
                choices = filterValues$summarise_cohort_attrition_grouping_cdm_name,
                selected = filterValues$summarise_cohort_attrition_grouping_cdm_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "summarise_cohort_attrition_grouping_cohort_name",
                label = "Cohort name",
                choices = filterValues$summarise_cohort_attrition_grouping_cohort_name,
                selected = filterValues$summarise_cohort_attrition_grouping_cohort_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "summarise_cohort_attrition_grouping_reason",
                label = "Reason",
                choices = filterValues$summarise_cohort_attrition_grouping_reason,
                selected = filterValues$summarise_cohort_attrition_grouping_reason,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "summarise_cohort_attrition_grouping_reason_id",
                label = "Reason id",
                choices = filterValues$summarise_cohort_attrition_grouping_reason_id,
                selected = filterValues$summarise_cohort_attrition_grouping_reason_id,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Variables",
              shinyWidgets::pickerInput(
                inputId = "summarise_cohort_attrition_variable_name",
                label = "Variable name",
                choices = filterValues$summarise_cohort_attrition_variable_name,
                selected = filterValues$summarise_cohort_attrition_variable_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Estimates",
              shinyWidgets::pickerInput(
                inputId = "summarise_cohort_attrition_estimate_name",
                label = "Estimate name",
                choices = filterValues$summarise_cohort_attrition_estimate_name,
                selected = filterValues$summarise_cohort_attrition_estimate_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            )
          )
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Tidy",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::downloadButton(outputId = "summarise_cohort_attrition_tidy_download", label = "Download csv")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_attrition_tidy_columns",
                    label = "Columns",
                    choices = filterValues$summarise_cohort_attrition_tidy_columns,
                    selected = filterValues$summarise_cohort_attrition_tidy_columns,
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::radioButtons(
                    inputId = "summarise_cohort_attrition_tidy_pivot",
                    label = "Pivot estimates/variables",
                    choices = c("none", "estimates", "estimates and variables"),
                    selected = "none"
                  ),
                  position = "right"
                ),
                DT::dataTableOutput("summarise_cohort_attrition_tidy")
              )
            )
          ),
          bslib::nav_panel(
            title = "Table cohort attrition",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_attrition_gt_3_download_type",
                    label = "File type",
                    selected = "docx",
                    choices = c("docx", "png", "pdf", "html"),
                    multiple = FALSE
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_attrition_gt_3_download", label = "Download")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "none",
                      labels = c("reason", "reason_id", "variable_level", "estimate_name"),
                      input_id = "summarise_cohort_attrition_gt_3_none"
                    ),
                    sortable::add_rank_list(
                      text = "header",
                      labels = "variable_name",
                      input_id = "summarise_cohort_attrition_gt_3_header"
                    ),
                    sortable::add_rank_list(
                      text = "groupColumn",
                      labels = c("cdm_name", "cohort_name"),
                      input_id = "summarise_cohort_attrition_gt_3_groupColumn"
                    ),
                    sortable::add_rank_list(
                      text = "hide",
                      labels = character(),
                      input_id = "summarise_cohort_attrition_gt_3_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_cohort_attrition_gt_3")
              )
            )
          ),
          bslib::nav_panel(
            title = "Diagram",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_cohort_attrition_grViz_4_download_width",
                    label = "Width (px)",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_cohort_attrition_grViz_4_download_height",
                    label = "Height (px)",
                    value = 10
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_attrition_grViz_4_download", label = "Download")
                ),
                class = "text-end"
              ),
              DiagrammeR::grVizOutput("summarise_cohort_attrition_grViz_4")
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Cohort code use",
      icon = shiny::icon("chart-column"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::accordion(
            bslib::accordion_panel(
              title = "Settings",
              shinyWidgets::pickerInput(
                inputId = "cohort_code_use_settings_timing",
                label = "Timing",
                choices = filterValues$cohort_code_use_settings_timing,
                selected = filterValues$cohort_code_use_settings_timing,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Grouping",
              shinyWidgets::pickerInput(
                inputId = "cohort_code_use_grouping_cdm_name",
                label = "Cdm name",
                choices = filterValues$cohort_code_use_grouping_cdm_name,
                selected = filterValues$cohort_code_use_grouping_cdm_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "cohort_code_use_grouping_cohort_name",
                label = "Cohort name",
                choices = filterValues$cohort_code_use_grouping_cohort_name,
                selected = filterValues$cohort_code_use_grouping_cohort_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "cohort_code_use_grouping_codelist_name",
                label = "Codelist name",
                choices = filterValues$cohort_code_use_grouping_codelist_name,
                selected = filterValues$cohort_code_use_grouping_codelist_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "cohort_code_use_grouping_source_concept_name",
                label = "Source concept name",
                choices = filterValues$cohort_code_use_grouping_source_concept_name,
                selected = filterValues$cohort_code_use_grouping_source_concept_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "cohort_code_use_grouping_source_concept_id",
                label = "Source concept id",
                choices = filterValues$cohort_code_use_grouping_source_concept_id,
                selected = filterValues$cohort_code_use_grouping_source_concept_id,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "cohort_code_use_grouping_source_concept_value",
                label = "Source concept value",
                choices = filterValues$cohort_code_use_grouping_source_concept_value,
                selected = filterValues$cohort_code_use_grouping_source_concept_value,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "cohort_code_use_grouping_domain_id",
                label = "Domain id",
                choices = filterValues$cohort_code_use_grouping_domain_id,
                selected = filterValues$cohort_code_use_grouping_domain_id,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Variables",
              shinyWidgets::pickerInput(
                inputId = "cohort_code_use_variable_name",
                label = "Variable name",
                choices = filterValues$cohort_code_use_variable_name,
                selected = filterValues$cohort_code_use_variable_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Estimates",
              shinyWidgets::pickerInput(
                inputId = "cohort_code_use_estimate_name",
                label = "Estimate name",
                choices = filterValues$cohort_code_use_estimate_name,
                selected = filterValues$cohort_code_use_estimate_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            )
          )
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Tidy",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::downloadButton(outputId = "cohort_code_use_tidy_download", label = "Download csv")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "cohort_code_use_tidy_columns",
                    label = "Columns",
                    choices = filterValues$cohort_code_use_tidy_columns,
                    selected = filterValues$cohort_code_use_tidy_columns,
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::radioButtons(
                    inputId = "cohort_code_use_tidy_pivot",
                    label = "Pivot estimates/variables",
                    choices = c("none", "estimates", "estimates and variables"),
                    selected = "none"
                  ),
                  position = "right"
                ),
                DT::dataTableOutput("cohort_code_use_tidy")
              )
            )
          ),
          bslib::nav_panel(
            title = "Table cohort code use",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "cohort_code_use_gt_12_download_type",
                    label = "File type",
                    selected = "docx",
                    choices = c("docx", "png", "pdf", "html"),
                    multiple = FALSE
                  ),
                  shiny::downloadButton(outputId = "cohort_code_use_gt_12_download", label = "Download")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "none",
                      labels = c("cohort_name", "codelist_name", "source_concept_name", "source_concept_id", "source_concept_value", "domain_id", "variable_name", "variable_level"),
                      input_id = "cohort_code_use_gt_12_none"
                    ),
                    sortable::add_rank_list(
                      text = "header",
                      labels = c("cdm_name", "estimate_name"),
                      input_id = "cohort_code_use_gt_12_header"
                    ),
                    sortable::add_rank_list(
                      text = "groupColumn",
                      labels = NULL,
                      input_id = "cohort_code_use_gt_12_groupColumn"
                    ),
                    sortable::add_rank_list(
                      text = "hide",
                      labels = character(),
                      input_id = "cohort_code_use_gt_12_hide"
                    )
                  ),
                  shiny::checkboxInput(
                    inputId = "cohort_code_use_gt_12_timing",
                    label = "timing",
                    value = c(FALSE)
                  ),
                  position = "right"
                ),
                gt::gt_output("cohort_code_use_gt_12")
              )
            )
          )
        )
      )
    )
  ),
  bslib::nav_menu(
    title = "Patient characteristics",
    icon = shiny::icon("list"),
    bslib::nav_panel(
      title = "Cohort characteristics",
      icon = shiny::icon("users-gear"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::accordion(
            bslib::accordion_panel(
              title = "Settings",
              shinyWidgets::pickerInput(
                inputId = "summarise_characteristics_settings_table_name",
                label = "Table name",
                choices = filterValues$summarise_characteristics_settings_table_name,
                selected = filterValues$summarise_characteristics_settings_table_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Grouping",
              shinyWidgets::pickerInput(
                inputId = "summarise_characteristics_grouping_cdm_name",
                label = "Cdm name",
                choices = filterValues$summarise_characteristics_grouping_cdm_name,
                selected = filterValues$summarise_characteristics_grouping_cdm_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "summarise_characteristics_grouping_cohort_name",
                label = "Cohort name",
                choices = filterValues$summarise_characteristics_grouping_cohort_name,
                selected = filterValues$summarise_characteristics_grouping_cohort_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "summarise_characteristics_grouping_table",
                label = "Table",
                choices = filterValues$summarise_characteristics_grouping_table,
                selected = filterValues$summarise_characteristics_grouping_table,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "summarise_characteristics_grouping_window",
                label = "Window",
                choices = filterValues$summarise_characteristics_grouping_window,
                selected = filterValues$summarise_characteristics_grouping_window,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "summarise_characteristics_grouping_value",
                label = "Value",
                choices = filterValues$summarise_characteristics_grouping_value,
                selected = filterValues$summarise_characteristics_grouping_value,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Variables",
              shinyWidgets::pickerInput(
                inputId = "summarise_characteristics_variable_name",
                label = "Variable name",
                choices = filterValues$summarise_characteristics_variable_name,
                selected = filterValues$summarise_characteristics_variable_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Estimates",
              shinyWidgets::pickerInput(
                inputId = "summarise_characteristics_estimate_name",
                label = "Estimate name",
                choices = filterValues$summarise_characteristics_estimate_name,
                selected = filterValues$summarise_characteristics_estimate_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            )
          )
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Tidy",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::downloadButton(outputId = "summarise_characteristics_tidy_download", label = "Download csv")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_tidy_columns",
                    label = "Columns",
                    choices = filterValues$summarise_characteristics_tidy_columns,
                    selected = filterValues$summarise_characteristics_tidy_columns,
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::radioButtons(
                    inputId = "summarise_characteristics_tidy_pivot",
                    label = "Pivot estimates/variables",
                    choices = c("none", "estimates", "estimates and variables"),
                    selected = "none"
                  ),
                  position = "right"
                ),
                DT::dataTableOutput("summarise_characteristics_tidy")
              )
            )
          ),
          bslib::nav_panel(
            title = "Table cohort characteristics",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_gt_7_download_type",
                    label = "File type",
                    selected = "docx",
                    choices = c("docx", "png", "pdf", "html"),
                    multiple = FALSE
                  ),
                  shiny::downloadButton(outputId = "summarise_characteristics_gt_7_download", label = "Download")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "none",
                      labels = c("table", "window", "value", "variable_name", "variable_level", "estimate_name"),
                      input_id = "summarise_characteristics_gt_7_none"
                    ),
                    sortable::add_rank_list(
                      text = "header",
                      labels = c("cdm_name", "cohort_name"),
                      input_id = "summarise_characteristics_gt_7_header"
                    ),
                    sortable::add_rank_list(
                      text = "groupColumn",
                      labels = character(),
                      input_id = "summarise_characteristics_gt_7_groupColumn"
                    ),
                    sortable::add_rank_list(
                      text = "hide",
                      labels = character(),
                      input_id = "summarise_characteristics_gt_7_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_characteristics_gt_7")
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot characteristics",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_characteristics_ggplot2_8_download_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_characteristics_ggplot2_8_download_height",
                    label = "Height",
                    value = 10
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_ggplot2_8_download_units",
                    label = "Units",
                    selected = "cm",
                    choices = c("px", "cm", "inch"),
                    multiple = FALSE
                  ),
                  shiny::numericInput(
                    inputId = "summarise_characteristics_ggplot2_8_download_dpi",
                    label = "dpi",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_characteristics_ggplot2_8_download", label = "Download")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_ggplot2_8_plotStyle",
                    label = "plotStyle",
                    selected = NULL,
                    multiple = FALSE,
                    choices = c("boxplot", "barplot", "scatterplot"),
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_ggplot2_8_facet",
                    label = "facet",
                    selected = NULL,
                    multiple = TRUE,
                    choices = c("cdm_name", "cohort_name", "table", "window", "value", "variable_name", "variable_level", "estimate_name", "table_name"),
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_ggplot2_8_colour",
                    label = "colour",
                    selected = NULL,
                    multiple = TRUE,
                    choices = c("cdm_name", "cohort_name", "table", "window", "value", "variable_name", "variable_level", "estimate_name", "table_name"),
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::plotOutput("summarise_characteristics_ggplot2_8")
              )
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Large Scale Characteristics",
      icon = shiny::icon("arrow-up-right-dots"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::accordion(
            bslib::accordion_panel(
              title = "Settings",
              shinyWidgets::pickerInput(
                inputId = "summarise_large_scale_characteristics_settings_analysis",
                label = "Analysis",
                choices = filterValues$summarise_large_scale_characteristics_settings_analysis,
                selected = filterValues$summarise_large_scale_characteristics_settings_analysis,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "summarise_large_scale_characteristics_settings_table_name",
                label = "Table name",
                choices = filterValues$summarise_large_scale_characteristics_settings_table_name,
                selected = filterValues$summarise_large_scale_characteristics_settings_table_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "summarise_large_scale_characteristics_settings_type",
                label = "Type",
                choices = filterValues$summarise_large_scale_characteristics_settings_type,
                selected = filterValues$summarise_large_scale_characteristics_settings_type,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Grouping",
              shinyWidgets::pickerInput(
                inputId = "summarise_large_scale_characteristics_grouping_cdm_name",
                label = "Cdm name",
                choices = filterValues$summarise_large_scale_characteristics_grouping_cdm_name,
                selected = filterValues$summarise_large_scale_characteristics_grouping_cdm_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "summarise_large_scale_characteristics_grouping_cohort_name",
                label = "Cohort name",
                choices = filterValues$summarise_large_scale_characteristics_grouping_cohort_name,
                selected = filterValues$summarise_large_scale_characteristics_grouping_cohort_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "summarise_large_scale_characteristics_grouping_concept_id",
                label = "Concept id",
                choices = filterValues$summarise_large_scale_characteristics_grouping_concept_id,
                selected = filterValues$summarise_large_scale_characteristics_grouping_concept_id,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Variables",
              shinyWidgets::pickerInput(
                inputId = "summarise_large_scale_characteristics_variable_name",
                label = "Variable name",
                choices = filterValues$summarise_large_scale_characteristics_variable_name,
                selected = filterValues$summarise_large_scale_characteristics_variable_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Estimates",
              shinyWidgets::pickerInput(
                inputId = "summarise_large_scale_characteristics_estimate_name",
                label = "Estimate name",
                choices = filterValues$summarise_large_scale_characteristics_estimate_name,
                selected = filterValues$summarise_large_scale_characteristics_estimate_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            )
          )
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Tidy",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::downloadButton(outputId = "summarise_large_scale_characteristics_tidy_download", label = "Download csv")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_tidy_columns",
                    label = "Columns",
                    choices = filterValues$summarise_large_scale_characteristics_tidy_columns,
                    selected = filterValues$summarise_large_scale_characteristics_tidy_columns,
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::radioButtons(
                    inputId = "summarise_large_scale_characteristics_tidy_pivot",
                    label = "Pivot estimates/variables",
                    choices = c("none", "estimates", "estimates and variables"),
                    selected = "none"
                  ),
                  position = "right"
                ),
                DT::dataTableOutput("summarise_large_scale_characteristics_tidy")
              )
            )
          ),
          bslib::nav_panel(
            title = "Formatted",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_gt_0_download_type",
                    label = "File type",
                    selected = "docx",
                    choices = c("docx", "png", "pdf", "html"),
                    multiple = FALSE
                  ),
                  shiny::downloadButton(outputId = "summarise_large_scale_characteristics_gt_0_download", label = "Download")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "none",
                      labels = c("concept_id", "variable_name", "variable_level", "estimate_name", "analysis", "table_name", "type"),
                      input_id = "summarise_large_scale_characteristics_gt_0_none"
                    ),
                    sortable::add_rank_list(
                      text = "header",
                      labels = "cdm_name",
                      input_id = "summarise_large_scale_characteristics_gt_0_header"
                    ),
                    sortable::add_rank_list(
                      text = "group",
                      labels = "cohort_name",
                      input_id = "summarise_large_scale_characteristics_gt_0_group"
                    ),
                    sortable::add_rank_list(
                      text = "hide",
                      labels = character(),
                      input_id = "summarise_large_scale_characteristics_gt_0_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_large_scale_characteristics_gt_0")
              )
            )
          )
        )
      )
    )
  ),
  bslib::nav_spacer(),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("download"),
      shiny::downloadButton(
        outputId = "download_raw",
        label = "Download raw data",
        icon = shiny::icon("download")
      )
    )
  ),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("circle-info"),
      shiny::tags$img(
        src = "hds_logo.svg",
        class = "logo-img",
        alt = "Logo",
        height = "auto",
        width = "30%",
        style = "float:right"
      ),
      "This shiny app was generated with ",
      shiny::a(
        "OmopViewer",
        href = "https://github.com/OHDSI/OmopViewer",
        target = "_blank"
      ),
      shiny::strong("v0.2.0")
    )
  ),
  bslib::nav_item(bslib::input_dark_mode(id = "dark_mode", mode = "light"))
)
